-- ════════════════════════════════════════════════════════════════
-- SyncPad – Fresh Production Database Baseline
-- ════════════════════════════════════════════════════════════════
-- Generated by concatenating the current numbered migrations in
-- supabase/migrations/ — 0001, 0002, 0003, 0004, 0005, 0006, 0008, in that
-- order. Every statement in every section below is idempotent (CREATE IF
-- NOT EXISTS / CREATE OR REPLACE / DROP POLICY IF EXISTS + CREATE POLICY),
-- so this whole file is safe to paste into the Supabase SQL Editor and run
-- in ONE shot for a brand-new project — no need to run 7 separate files in
-- order, and no historical migration-numbering questions to work through.
--
-- Verified: run twice in a row against a real Postgres 16 server (stubbed
-- with minimal auth/storage schemas standing in for the Supabase platform
-- pieces this SQL assumes exist) — zero errors either time, confirming both
-- that the concatenation is syntactically sound and that the whole file is
-- genuinely idempotent, not just each individual section in isolation.
--
-- Excluded on purpose:
--   • 0007_room_edit_tokens.sql — a since-reverted write-gating model.
--     Historical/inert infrastructure, unused by the current client. See
--     0009's header and CHANGELOG.md's Phase 26 entry for the full story.
--   • 0009_revert_edit_token_write_gating.sql — only needed by a project
--     that previously ran 0007. A fresh project that never ran 0007 has
--     nothing to revert.
--
-- Each section below keeps its source file's own header comment intact
-- (design rationale worth having in one place), including a few
-- "run this AFTER 0001_base_schema.sql has been applied" notes that are
-- inherently true here too — 0001's section always runs first in this
-- file — so nothing extra needs to be done to satisfy them.
--
-- WHICH FILE TO USE, WHEN
-- ─────────────────────────
--   • Brand-new Supabase project → run THIS file once, then skip to
--     "Step 3 — Configure credentials" in DEPLOYMENT.md.
--   • Existing SyncPad deployment → keep using the individual numbered
--     files in supabase/migrations/ going forward for anything new; do
--     NOT re-run this baseline file against a database that already has
--     data (it is safe to — every statement is idempotent — but there is
--     no reason to; use the specific migration for whatever's new instead).
--   • Deciding which optional migrations to apply to an EXISTING project
--     one at a time → see the table in DEPLOYMENT.md's
--     "Optional feature migrations" section, which explains what each one
--     enables and what happens if it's skipped.
--
-- Regenerating this file after adding a new numbered migration: append the
-- new migration's content as its own section below (excluding another
-- historical/reverted one, same as 0007/0009 here), keep the "Excluded on
-- purpose" note current, and update DEPLOYMENT.md if the file list changes.
-- ════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0001_base_schema.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Supabase Setup SQL
-- SAFE TO RERUN: all statements are idempotent.
-- Run this in your Supabase project → SQL Editor.
-- ============================================================

-- ── Extensions ───────────────────────────────────────────────

create extension if not exists "pgcrypto";


-- Optional scheduler support:
-- For automatic expired-room cleanup, enable the `pg_cron` extension in
-- Supabase Dashboard → Database → Extensions before running this file.
-- The scheduling block later in this script detects whether pg_cron is
-- available and skips scheduling safely if it is not enabled.

-- ── Tables ───────────────────────────────────────────────────

create table if not exists syncpad_rooms (
  room_id              text        primary key,
  room_name            text        not null default '',
  content              text        not null default '',
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  created_by_device    text,
  updated_by_device    text,
  passcode_hash        text,
  passcode_salt        text,
  encryption_enabled   boolean     not null default false,
  encryption_salt      text,
  expires_at           timestamptz,
  view_once            boolean     not null default false,
  viewed               boolean     not null default false,
  editing_locked       boolean     not null default false,
  cleared_reason       text        -- 'expired' | 'view_once' | 'manual' | null
);

-- Safe to rerun on older installs that pre-date editing_locked.
alter table syncpad_rooms
  add column if not exists editing_locked boolean not null default false;

alter table syncpad_rooms
  add column if not exists passcode_salt text;


create table if not exists public.syncpad_room_reports (
  id uuid primary key default gen_random_uuid(),
  room_id text not null,
  share_token text,
  report_reason text not null,
  report_details text,
  reporter_device_id text,
  reporter_mode text not null default 'editable' check (reporter_mode in ('editable', 'readonly')),
  page_url text,
  user_agent text,
  created_at timestamptz not null default now(),
  status text not null default 'new'
);


-- DB-side validation for anonymous room reports (keep in sync with frontend).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'syncpad_room_reports_reason_check'
  ) then
    alter table public.syncpad_room_reports
      add constraint syncpad_room_reports_reason_check
      check (report_reason in ('Spam', 'Abuse or harassment', 'Illegal or harmful content', 'Private information', 'Other'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'syncpad_room_reports_mode_check'
  ) then
    alter table public.syncpad_room_reports
      add constraint syncpad_room_reports_mode_check
      check (reporter_mode in ('editable', 'readonly'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'syncpad_room_reports_details_len_check'
  ) then
    alter table public.syncpad_room_reports
      add constraint syncpad_room_reports_details_len_check
      check (report_details is null or length(report_details) <= 1000);
  end if;
end $$;

create table if not exists syncpad_files (
  id                   uuid        primary key default gen_random_uuid(),
  room_id              text        not null references syncpad_rooms(room_id) on delete cascade,
  filename             text        not null,
  file_path            text        not null,
  file_size            bigint      not null default 0,
  mime_type            text        not null default 'application/octet-stream',
  uploaded_by_device   text,
  uploaded_at          timestamptz not null default now()
);

-- NOTE: ON DELETE CASCADE on syncpad_files removes the metadata rows when a
-- room is deleted from syncpad_rooms. It does NOT remove the physical files
-- in the syncpad-files Storage bucket. Those must be cleaned up separately
-- (e.g. via a Supabase Edge Function or manual bucket management).

-- ── Indexes ──────────────────────────────────────────────────

create index if not exists idx_syncpad_files_room_id
  on syncpad_files(room_id);

create index if not exists idx_syncpad_room_reports_created_at
  on public.syncpad_room_reports(created_at);
create index if not exists idx_syncpad_room_reports_room_id
  on public.syncpad_room_reports(room_id);
create index if not exists idx_syncpad_room_reports_status
  on public.syncpad_room_reports(status);


-- Database owns syncpad_rooms.updated_at on every UPDATE to prevent
-- client clocks or client-supplied timestamps from skewing reconciliation.
create or replace function public.set_syncpad_rooms_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
      from pg_trigger
     where tgname = 'syncpad_rooms_set_updated_at'
       and tgrelid = 'public.syncpad_rooms'::regclass
  ) then
    create trigger syncpad_rooms_set_updated_at
      before update on public.syncpad_rooms
      for each row
      execute function public.set_syncpad_rooms_updated_at();
  end if;
end $$;

create index if not exists idx_syncpad_rooms_expires
  on syncpad_rooms(expires_at)
  where expires_at is not null;

-- ── Row-Level Security ────────────────────────────────────────

alter table syncpad_rooms enable row level security;
alter table syncpad_files enable row level security;
alter table if exists public.syncpad_room_reports enable row level security;
alter table if exists public.syncpad_share_links enable row level security;



-- Optional/future admin support only: current frontend `/admin` route is a placeholder.
-- Keep these objects for possible future authenticated maintenance tooling.
create table if not exists public.syncpad_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

alter table public.syncpad_admins enable row level security;

drop policy if exists "admins can read own admin row" on public.syncpad_admins;
create policy "admins can read own admin row"
  on public.syncpad_admins for select to authenticated
  using (auth.uid() = user_id);

create or replace function public.is_syncpad_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.syncpad_admins a where a.user_id = auth.uid()
  );
$$;

grant execute on function public.is_syncpad_admin() to authenticated;

-- Server-side enforcement of the room lock. Everything else that gates
-- writes (read-only share links, ?mode=read, encryption-without-key) is a
-- UX-only frontend control by design — see docs/security.md — because
-- there is no per-visitor identity to check against; a room's editable and
-- read-only links both resolve to the same room_id with the same anon key.
-- editing_locked is different: it's server-stored room state, not a
-- property of which link someone followed, so it CAN be enforced here.
-- This trigger is a defense-in-depth backstop for anyone bypassing the
-- frontend and calling the REST API directly — the normal UI already
-- blocks locked-room edits via permissions.js / canEdit() before a request
-- is ever sent.
--
-- 'backend-cleanup' (see cleanup_expired_syncpad_rooms below) and admins
-- (is_syncpad_admin()) are exempt so expiry cleanup and admin moderation
-- can still clear a locked room's content.
create or replace function public.enforce_syncpad_rooms_lock()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if OLD.editing_locked
     and NEW.editing_locked
     and NEW.content is distinct from OLD.content
     and coalesce(NEW.updated_by_device, '') <> 'backend-cleanup'
     and not public.is_syncpad_admin()
  then
    raise exception 'This room is locked for editing.' using errcode = '42501';
  end if;
  return NEW;
end;
$$;

do $$
begin
  if not exists (
    select 1
      from pg_trigger
     where tgname = 'syncpad_rooms_enforce_lock'
       and tgrelid = 'public.syncpad_rooms'::regclass
  ) then
    create trigger syncpad_rooms_enforce_lock
      before update on public.syncpad_rooms
      for each row
      execute function public.enforce_syncpad_rooms_lock();
  end if;
end $$;

create table if not exists public.syncpad_share_links (
  id uuid primary key default gen_random_uuid(),
  room_id text not null references public.syncpad_rooms(room_id) on delete cascade,
  token text unique not null,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  disabled boolean not null default false
);

create unique index if not exists idx_syncpad_share_links_room_id
  on public.syncpad_share_links(room_id);
create unique index if not exists idx_syncpad_share_links_token
  on public.syncpad_share_links(token);
create index if not exists idx_syncpad_share_links_created_at
  on public.syncpad_share_links(created_at);

drop policy if exists "anon no direct share-link reads" on public.syncpad_share_links;
drop policy if exists "anon no direct share-link writes" on public.syncpad_share_links;

create policy "anon no direct share-link reads"
  on public.syncpad_share_links for select to anon using (false);
create policy "anon no direct share-link writes"
  on public.syncpad_share_links for all to anon using (false) with check (false);

create or replace function public.get_or_create_readonly_share_link(p_room_id text)
returns table(token text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
begin
  if p_room_id is null or btrim(p_room_id) = '' then
    return;
  end if;

  select sl.token into v_token
    from public.syncpad_share_links sl
   where sl.room_id = p_room_id and sl.disabled = false
   limit 1;

  if v_token is null then
    v_token := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
    insert into public.syncpad_share_links(room_id, token)
    values (p_room_id, v_token)
    on conflict (room_id) do update set disabled = false
    returning syncpad_share_links.token into v_token;
  end if;

  return query select v_token;
end;
$$;

create or replace function public.resolve_readonly_share_link(p_token text)
returns table(room_id text, content text, updated_at timestamptz, encryption_enabled boolean, encryption_salt text, passcode_hash text, passcode_salt text, view_once boolean, viewed boolean, editing_locked boolean, cleared_reason text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_token is null or btrim(p_token) = '' then
    return;
  end if;

  update public.syncpad_share_links
     set last_used_at = now()
   where token = p_token and disabled = false;

  return query
  select r.room_id, r.content, r.updated_at, r.encryption_enabled, r.encryption_salt, r.passcode_hash, r.passcode_salt, r.view_once, r.viewed, r.editing_locked, r.cleared_reason, r.expires_at
    from public.syncpad_share_links sl
    join public.syncpad_rooms r on r.room_id = sl.room_id
   where sl.token = p_token and sl.disabled = false
   limit 1;
end;
$$;

grant execute on function public.get_or_create_readonly_share_link(text) to anon, authenticated;
grant execute on function public.resolve_readonly_share_link(text) to anon, authenticated;

-- Drop-and-recreate makes this script idempotent without needing
-- "create policy if not exists" (which is not supported in all PG versions).

drop policy if exists "anon read rooms"   on syncpad_rooms;
drop policy if exists "anon insert rooms" on syncpad_rooms;
drop policy if exists "anon update rooms" on syncpad_rooms;

create policy "anon read rooms"
  on syncpad_rooms for select to anon using (true);

create policy "anon insert rooms"
  on syncpad_rooms for insert to anon with check (true);

create policy "anon update rooms"
  on syncpad_rooms for update to anon using (true) with check (true);

drop policy if exists "anon read files"   on syncpad_files;
drop policy if exists "anon insert files" on syncpad_files;
drop policy if exists "anon delete files" on syncpad_files;

create policy "anon read files"
  on syncpad_files for select to anon using (true);

create policy "anon insert files"
  on syncpad_files for insert to anon with check (true);

create policy "anon delete files"
  on syncpad_files for delete to anon using (true);

-- ── Authenticated baseline policies ──────────────────────────
-- After an admin signs in at /admin, the Supabase client holds an
-- authenticated session for the rest of the browsing session.
-- The shared anon-key client then sends requests as `authenticated`
-- instead of `anon`, which means the anon policies above no longer
-- apply — so normal room/file operations would fail with RLS errors.
-- These policies give every authenticated user the same baseline
-- access as anon for the normal app features.
-- Admin-only actions (update/delete by admin) are still gated by
-- is_syncpad_admin() in the admin-specific policies below.

drop policy if exists "authenticated baseline read rooms"   on syncpad_rooms;
drop policy if exists "authenticated baseline insert rooms" on syncpad_rooms;
drop policy if exists "authenticated baseline update rooms" on syncpad_rooms;
create policy "authenticated baseline read rooms"
  on syncpad_rooms for select to authenticated using (true);
create policy "authenticated baseline insert rooms"
  on syncpad_rooms for insert to authenticated with check (true);
create policy "authenticated baseline update rooms"
  on syncpad_rooms for update to authenticated using (true) with check (true);

drop policy if exists "authenticated baseline read files"   on syncpad_files;
drop policy if exists "authenticated baseline insert files" on syncpad_files;
drop policy if exists "authenticated baseline delete files" on syncpad_files;
create policy "authenticated baseline read files"
  on syncpad_files for select to authenticated using (true);
create policy "authenticated baseline insert files"
  on syncpad_files for insert to authenticated with check (true);
create policy "authenticated baseline delete files"
  on syncpad_files for delete to authenticated using (true);

-- ── Admin-only policies ────────────────────────────────────────
-- These allow admins to perform elevated actions (delete rooms,
-- update files metadata, etc.) that the baseline policies above
-- do not need to grant. The is_syncpad_admin() check ensures only
-- users in the syncpad_admins table can invoke these.

drop policy if exists "admin read rooms" on syncpad_rooms;
drop policy if exists "admin update rooms" on syncpad_rooms;
drop policy if exists "admin delete rooms" on syncpad_rooms;
create policy "admin read rooms" on syncpad_rooms for select to authenticated using (public.is_syncpad_admin());
create policy "admin update rooms" on syncpad_rooms for update to authenticated using (public.is_syncpad_admin()) with check (public.is_syncpad_admin());
create policy "admin delete rooms" on syncpad_rooms for delete to authenticated using (public.is_syncpad_admin());

drop policy if exists "admin read files" on syncpad_files;
drop policy if exists "admin update files" on syncpad_files;
drop policy if exists "admin delete files" on syncpad_files;
create policy "admin read files" on syncpad_files for select to authenticated using (public.is_syncpad_admin());
create policy "admin update files" on syncpad_files for update to authenticated using (public.is_syncpad_admin()) with check (public.is_syncpad_admin());
create policy "admin delete files" on syncpad_files for delete to authenticated using (public.is_syncpad_admin());

drop policy if exists "anon insert room reports" on public.syncpad_room_reports;
create policy "anon insert room reports"
  on public.syncpad_room_reports for insert to anon with check (true);

-- Future-only admin review access for reported rooms.
drop policy if exists "admin read room reports" on public.syncpad_room_reports;
drop policy if exists "admin update room reports" on public.syncpad_room_reports;
drop policy if exists "admin delete room reports" on public.syncpad_room_reports;
create policy "admin read room reports" on public.syncpad_room_reports for select to authenticated using (public.is_syncpad_admin());
create policy "admin update room reports" on public.syncpad_room_reports for update to authenticated using (public.is_syncpad_admin()) with check (public.is_syncpad_admin());
create policy "admin delete room reports" on public.syncpad_room_reports for delete to authenticated using (public.is_syncpad_admin());

drop policy if exists "admin read share-links" on public.syncpad_share_links;
drop policy if exists "admin update share-links" on public.syncpad_share_links;
drop policy if exists "admin delete share-links" on public.syncpad_share_links;
create policy "admin read share-links" on public.syncpad_share_links for select to authenticated using (public.is_syncpad_admin());
create policy "admin update share-links" on public.syncpad_share_links for update to authenticated using (public.is_syncpad_admin()) with check (public.is_syncpad_admin());
create policy "admin delete share-links" on public.syncpad_share_links for delete to authenticated using (public.is_syncpad_admin());


-- ── Backend expired-room cleanup ──────────────────────────────
-- The browser still clears expired rooms immediately when a user opens one.
-- This database function is the backend safety net for rooms that expire while
-- nobody is online.
--
-- Important encryption detail:
-- The database cannot create an encrypted empty payload because it never knows
-- the user's passphrase. Therefore:
--   • unencrypted expired rooms are cleared in place
--   • encrypted expired rooms are deleted so ciphertext is removed server-side
--
-- Deleting a room cascades syncpad_files metadata rows, but physical Storage
-- objects may still need separate Storage cleanup if the room had attachments.

create or replace function public.cleanup_expired_syncpad_rooms()
returns table(cleared_unencrypted integer, deleted_encrypted integer)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.syncpad_rooms
     set content = '',
         updated_at = now(),
         updated_by_device = 'backend-cleanup',
         cleared_reason = 'expired',
         expires_at = null
   where expires_at is not null
     and expires_at <= now()
     and coalesce(encryption_enabled, false) = false
     and cleared_reason is distinct from 'expired';

  get diagnostics cleared_unencrypted = row_count;

  delete from public.syncpad_rooms
   where expires_at is not null
     and expires_at <= now()
     and coalesce(encryption_enabled, false) = true;

  get diagnostics deleted_encrypted = row_count;

  return next;
end;
$$;

comment on function public.cleanup_expired_syncpad_rooms()
  is 'Clears unencrypted expired rooms and deletes encrypted expired rooms. Intended for pg_cron or manual SQL maintenance.';

-- Do not expose maintenance cleanup as a public app capability. The scheduled
-- pg_cron job and SQL Editor owner can still run it.
revoke all on function public.cleanup_expired_syncpad_rooms() from public;
revoke all on function public.cleanup_expired_syncpad_rooms() from anon;
revoke all on function public.cleanup_expired_syncpad_rooms() from authenticated;

-- Try to schedule the cleanup every 10 minutes if pg_cron is already enabled.
-- If pg_cron is not enabled, this block only prints a NOTICE and the rest of
-- the setup remains usable. To enable later: Database → Extensions → pg_cron,
-- then rerun this setup file or run the cron.schedule call manually.

do $do$
declare
  existing_job_id bigint;
begin
  if not exists (select 1 from pg_extension where extname = 'pg_cron') then
    raise notice 'pg_cron is not enabled; automatic expired-room cleanup was not scheduled. Enable pg_cron and rerun this script to schedule it.';
    return;
  end if;

  select jobid
    into existing_job_id
    from cron.job
   where jobname = 'syncpad-expired-room-cleanup'
   limit 1;

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'syncpad-expired-room-cleanup',
    '*/10 * * * *',
    $job$select public.cleanup_expired_syncpad_rooms();$job$
  );
exception
  when others then
    raise notice 'Could not schedule syncpad expired-room cleanup: %', SQLERRM;
end;
$do$;

-- ── Realtime ─────────────────────────────────────────────────
-- These statements fail if the table is already in the publication.
-- The DO blocks catch the "duplicate_object" error so the script is
-- safe to rerun.

do $$
begin
  alter publication supabase_realtime add table syncpad_rooms;
exception
  when duplicate_object then
    -- table is already in the publication; nothing to do
    null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table syncpad_files;
exception
  when duplicate_object then
    null;
end;
$$;

-- ── Storage bucket ────────────────────────────────────────────
-- The bucket insert is already idempotent via ON CONFLICT DO NOTHING.

insert into storage.buckets (id, name, public)
  values ('syncpad-files', 'syncpad-files', false)
  on conflict (id) do nothing;

-- Storage policies (drop-and-recreate for idempotency)

drop policy if exists "anon upload syncpad files" on storage.objects;
drop policy if exists "anon read syncpad files"   on storage.objects;
drop policy if exists "anon delete syncpad files" on storage.objects;

create policy "anon upload syncpad files"
  on storage.objects for insert to anon
  with check (bucket_id = 'syncpad-files');

create policy "anon read syncpad files"
  on storage.objects for select to anon
  using (bucket_id = 'syncpad-files');

create policy "anon delete syncpad files"
  on storage.objects for delete to anon
  using (bucket_id = 'syncpad-files');

-- Authenticated baseline Storage policies.
-- After admin sign-in the Supabase client uses the authenticated role,
-- so the anon storage policies above no longer apply. Mirror them here
-- so file upload/read/delete continues to work for authenticated users.

drop policy if exists "authenticated upload syncpad files" on storage.objects;
drop policy if exists "authenticated read syncpad files"   on storage.objects;
drop policy if exists "authenticated delete syncpad files" on storage.objects;

create policy "authenticated upload syncpad files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'syncpad-files');

create policy "authenticated read syncpad files"
  on storage.objects for select to authenticated
  using (bucket_id = 'syncpad-files');

create policy "authenticated delete syncpad files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'syncpad-files');

-- ════════════════════════════════════════════════════════════════
-- OPTIONAL: Maintenance queries (run manually as needed)
-- ════════════════════════════════════════════════════════════════
-- These are *not* part of the public app. Run them manually in the
-- SQL editor; do NOT expose them through the anon role.
--
-- -- 1) Manually run expired-room cleanup now
-- select * from public.cleanup_expired_syncpad_rooms();
--
-- -- 2) Check whether the pg_cron cleanup job exists
-- select jobid, jobname, schedule, active
-- from cron.job
-- where jobname = 'syncpad-expired-room-cleanup';
--
-- -- 3) Find rooms that have not been updated in 90+ days
-- select room_id, updated_at, length(content) as content_len
-- from   syncpad_rooms
-- where  updated_at < now() - interval '90 days'
-- order  by updated_at asc
-- limit  200;
--
-- -- 4) Find rooms that have been cleared and are very old
-- select room_id, cleared_reason, updated_at
-- from   syncpad_rooms
-- where  cleared_reason is not null
--   and  updated_at < now() - interval '30 days';
--
-- -- 5) Delete inactive rooms older than 180 days (CAREFUL — irreversible)
-- --    Run query #3 first to confirm the candidates.
-- -- delete from syncpad_rooms
-- -- where updated_at < now() - interval '180 days';
--
-- NOTE: Deleting a syncpad_rooms row cascades syncpad_files metadata, but it
-- does NOT reliably clean physical objects from the syncpad-files Storage
-- bucket. Use the Storage admin UI or a service-role Edge Function for
-- physical Storage cleanup.


create or replace function public.run_cleanup_expired_syncpad_rooms_as_admin()
returns table(cleared_unencrypted integer, deleted_encrypted integer)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_syncpad_admin() then
    raise exception 'not authorized';
  end if;
  return query select * from public.cleanup_expired_syncpad_rooms();
end;
$$;

grant execute on function public.run_cleanup_expired_syncpad_rooms_as_admin() to authenticated;


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0002_short_room_codes.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Short Room Codes Migration
-- SAFE TO RERUN: all statements use CREATE IF NOT EXISTS,
-- CREATE OR REPLACE, and DROP POLICY IF EXISTS / CREATE POLICY
-- so the script is fully idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER the
-- base 0001_base_schema.sql has been applied.
--
-- What this migration adds
-- ────────────────────────
--   A short (6-character), human-typeable/speakable code as a companion
--   to a room's full link — e.g. reading "K7X-9BQ" aloud on a call, or
--   typing it on a phone, is easier than a long URL. Opt-in and generated
--   on demand (same model as the existing read-only share link, NOT
--   auto-created for every room), because it's a *second* bearer credential
--   for the room and every room that has one is one more thing that can be
--   guessed/enumerated.
--
--   Security note: a code is drawn from a 30-symbol alphabet (excludes
--   0/O/1/I/L/U to avoid misreads), so 6 characters is 30^6 ≈ 729 million
--   combinations — the same order of magnitude as the random suffix
--   already used in client-generated room ids (utils.js's generateRoomId,
--   36^6 ≈ 2.18 billion), not a materially weaker access path. Resolving a
--   code only ever returns the plain room_id — the client then loads that
--   room through the exact same passcode/encryption gate a normal room
--   visit goes through. A code is not a separate, higher-trust grant.
--
--   1. syncpad_room_codes table
--      One optional row per room. RLS locked down like syncpad_share_links
--      — no direct anon/authenticated table access, only through the two
--      SECURITY DEFINER functions below.
--
--   2. get_or_create_room_code(room_id) — returns the room's existing code,
--      or generates, stores, and returns a new one. Retries on the rare
--      collision instead of trusting the random draw to be unique.
--
--   3. resolve_room_code(code) — the landing page's "Join by code" lookup.
--      Returns only room_id, nothing else, so it cannot be used to bypass
--      a room's passcode/encryption the way loading a room directly can't
--      either.
-- ============================================================

create table if not exists public.syncpad_room_codes (
  room_id     text        primary key references public.syncpad_rooms(room_id) on delete cascade,
  code        text        not null,
  created_at  timestamptz not null default now()
);

create unique index if not exists idx_syncpad_room_codes_code
  on public.syncpad_room_codes(code);

alter table public.syncpad_room_codes enable row level security;

drop policy if exists "anon no direct room-code reads" on public.syncpad_room_codes;
drop policy if exists "anon no direct room-code writes" on public.syncpad_room_codes;

create policy "anon no direct room-code reads"
  on public.syncpad_room_codes for select to anon using (false);
create policy "anon no direct room-code writes"
  on public.syncpad_room_codes for all to anon using (false) with check (false);

create or replace function public.get_or_create_room_code(p_room_id text)
returns table(code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code      text;
  v_alphabet  text := '23456789ABCDEFGHJKMNPQRSTVWXYZ'; -- excludes 0/O/1/I/L/U
  v_candidate text;
  v_attempt   int  := 0;
begin
  if p_room_id is null or btrim(p_room_id) = '' then
    return;
  end if;

  select rc.code into v_code
    from public.syncpad_room_codes rc
   where rc.room_id = p_room_id
   limit 1;

  while v_code is null and v_attempt < 10 loop
    v_attempt := v_attempt + 1;
    v_candidate := '';
    for i in 1..6 loop
      v_candidate := v_candidate || substr(v_alphabet, (floor(random() * length(v_alphabet)) + 1)::int, 1);
    end loop;

    begin
      insert into public.syncpad_room_codes(room_id, code)
      values (p_room_id, v_candidate);
      v_code := v_candidate;
    exception
      when unique_violation then
        -- Either a concurrent call already gave this room a code (room_id
        -- conflict) or v_candidate collided with another room's code (the
        -- unique index on code) — either way, check for this room's code
        -- and retry the loop if it's still not there.
        select rc.code into v_code
          from public.syncpad_room_codes rc
         where rc.room_id = p_room_id
         limit 1;
    end;
  end loop;

  return query select v_code;
end;
$$;

create or replace function public.resolve_room_code(p_code text)
returns table(room_id text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_code is null or btrim(p_code) = '' then
    return;
  end if;

  return query
  select rc.room_id
    from public.syncpad_room_codes rc
   where rc.code = upper(btrim(p_code))
   limit 1;
end;
$$;

grant execute on function public.get_or_create_room_code(text) to anon, authenticated;
grant execute on function public.resolve_room_code(text) to anon, authenticated;

comment on table public.syncpad_room_codes
  is 'Optional short human-typeable code per room, generated on demand via get_or_create_room_code(). resolve_room_code() is the only read path and returns just room_id — the code is an alternate spelling of the room link, not a separate access grant.';


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0003_room_comments.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Ephemeral Room Comments Migration
-- SAFE TO RERUN: all statements use CREATE IF NOT EXISTS,
-- CREATE OR REPLACE, and DROP POLICY IF EXISTS / CREATE POLICY
-- so the script is fully idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER the
-- base 0001_base_schema.sql has been applied.
--
-- What this migration adds
-- ────────────────────────
--   Lightweight comments anchored to a text range in the note — Notion/
--   Google Docs' most-requested pattern, but scoped to fit SyncPad's
--   ephemeral identity instead of becoming a permanent separate discussion
--   system: a comment has no independent lifetime of its own. It cascades
--   away the moment its room does (expiry, view-once, device-limit, or
--   manual deletion — all of them already just delete/clear the
--   syncpad_rooms row or rely on the FK cascade), and its `text` column
--   holds ciphertext for an encrypted room exactly like syncpad_rooms.content
--   and syncpad_room_revisions.content already do — the client encrypts
--   with the same room passphrase-derived key before insert, so this table
--   needs no separate encryption handling of its own.
--
--   No per-user auth in this app (see syncpad_rooms/syncpad_files RLS), so
--   access control here is identical to those tables: anyone who can reach
--   the room (by link, passcode, or decryption key) can read, add, and
--   delete comments — there's no concept of "your own comment" to protect
--   from other legitimate room participants.
--
--   anchor_from/anchor_to are character offsets into the *plain* markdown
--   string (matching cursor_pos/cursor_anchor in presence.js), so a comment
--   anchored to a range can be rendered as a decoration in the CM6 live
--   surface — see live-editor.js — the same way remote selections are.
-- ============================================================

create table if not exists public.syncpad_room_comments (
  id           uuid        primary key default gen_random_uuid(),
  room_id      text        not null references public.syncpad_rooms(room_id) on delete cascade,
  anchor_from  integer     not null,
  anchor_to    integer     not null,
  text         text        not null,
  device_id    text,
  device_name  text,
  created_at   timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'syncpad_room_comments_text_len_check'
  ) then
    alter table public.syncpad_room_comments
      add constraint syncpad_room_comments_text_len_check
      check (length(text) <= 4000); -- generous headroom over ciphertext's base64 overhead for a short comment
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'syncpad_room_comments_anchor_check'
  ) then
    alter table public.syncpad_room_comments
      add constraint syncpad_room_comments_anchor_check
      check (anchor_from >= 0 and anchor_to >= anchor_from);
  end if;
end $$;

create index if not exists idx_syncpad_room_comments_room_id_created_at
  on public.syncpad_room_comments(room_id, created_at);

alter table public.syncpad_room_comments enable row level security;

drop policy if exists "anon read comments"   on public.syncpad_room_comments;
drop policy if exists "anon insert comments" on public.syncpad_room_comments;
drop policy if exists "anon delete comments" on public.syncpad_room_comments;

create policy "anon read comments"
  on public.syncpad_room_comments for select to anon using (true);
create policy "anon insert comments"
  on public.syncpad_room_comments for insert to anon with check (true);
create policy "anon delete comments"
  on public.syncpad_room_comments for delete to anon using (true);

drop policy if exists "authenticated baseline read comments"   on public.syncpad_room_comments;
drop policy if exists "authenticated baseline insert comments" on public.syncpad_room_comments;
drop policy if exists "authenticated baseline delete comments" on public.syncpad_room_comments;

create policy "authenticated baseline read comments"
  on public.syncpad_room_comments for select to authenticated using (true);
create policy "authenticated baseline insert comments"
  on public.syncpad_room_comments for insert to authenticated with check (true);
create policy "authenticated baseline delete comments"
  on public.syncpad_room_comments for delete to authenticated using (true);

drop policy if exists "admin delete comments" on public.syncpad_room_comments;
create policy "admin delete comments"
  on public.syncpad_room_comments for delete to authenticated using (public.is_syncpad_admin());

-- Realtime: lets the Comments panel live-update across devices via
-- postgres_changes, the same mechanism subscribeToRoom()/subscribeToFiles()
-- already use for syncpad_rooms/syncpad_files.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime' and tablename = 'syncpad_room_comments'
  ) then
    alter publication supabase_realtime add table public.syncpad_room_comments;
  end if;
end $$;

comment on table public.syncpad_room_comments
  is 'Comments anchored to a text range in a room''s note. No independent lifetime — cascades away when the room does. text is ciphertext for an encrypted room, same as syncpad_rooms.content.';


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0004_version_history.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Version History Migration
-- SAFE TO RERUN: all statements use CREATE IF NOT EXISTS,
-- CREATE OR REPLACE, and DROP POLICY IF EXISTS / CREATE POLICY
-- so the script is fully idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER the
-- base 0001_base_schema.sql has been applied.
--
-- What this migration adds
-- ────────────────────────
--   1. syncpad_room_revisions table
--      One row per saved snapshot of a room's content, so past
--      versions can be listed and restored from the History
--      panel. `content` holds exactly what the client would
--      otherwise write to syncpad_rooms.content — for encrypted
--      rooms that is ciphertext, same as the live room row, so
--      this table needs no separate encryption handling.
--
--   2. Auto-pruning trigger
--      Keeps only the most recent N revisions per room (default
--      50) so history storage doesn't grow unbounded. Runs as
--      SECURITY DEFINER so it can prune rows regardless of the
--      inserting role's own RLS grants.
--
--   3. RLS policies
--      Anon/authenticated baseline read + insert, mirroring the
--      permissive model already used for syncpad_rooms and
--      syncpad_files (this app has no per-user auth — access
--      control is by room-ID/passcode knowledge, enforced
--      client-side). Delete is admin-only, matching the other
--      tables' admin policies.
-- ============================================================

create table if not exists public.syncpad_room_revisions (
  id          uuid        primary key default gen_random_uuid(),
  room_id     text        not null references public.syncpad_rooms(room_id) on delete cascade,
  content     text        not null default '',
  created_at  timestamptz not null default now(),
  device_id   text
);

create index if not exists idx_syncpad_room_revisions_room_id_created_at
  on public.syncpad_room_revisions(room_id, created_at desc);

alter table public.syncpad_room_revisions enable row level security;

-- ── RLS: anon baseline ──────────────────────────────────────
drop policy if exists "anon read room revisions"   on public.syncpad_room_revisions;
drop policy if exists "anon insert room revisions" on public.syncpad_room_revisions;

create policy "anon read room revisions"
  on public.syncpad_room_revisions for select to anon using (true);

create policy "anon insert room revisions"
  on public.syncpad_room_revisions for insert to anon with check (true);

-- ── RLS: authenticated baseline ─────────────────────────────
-- Same reasoning as syncpad_rooms/syncpad_files: once an admin signs in,
-- the shared client sends requests as `authenticated`, so normal room
-- usage (including saving revisions) needs the same baseline access.
drop policy if exists "authenticated baseline read room revisions"   on public.syncpad_room_revisions;
drop policy if exists "authenticated baseline insert room revisions" on public.syncpad_room_revisions;

create policy "authenticated baseline read room revisions"
  on public.syncpad_room_revisions for select to authenticated using (true);

create policy "authenticated baseline insert room revisions"
  on public.syncpad_room_revisions for insert to authenticated with check (true);

-- ── RLS: admin-only delete ──────────────────────────────────
drop policy if exists "admin delete room revisions" on public.syncpad_room_revisions;

create policy "admin delete room revisions"
  on public.syncpad_room_revisions for delete to authenticated
  using (public.is_syncpad_admin());

-- ── Auto-prune: keep only the most recent 50 revisions per room ─────
create or replace function public.prune_syncpad_room_revisions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.syncpad_room_revisions
   where room_id = new.room_id
     and id not in (
       select id from public.syncpad_room_revisions
        where room_id = new.room_id
        order by created_at desc
        limit 50
     );
  return null; -- AFTER trigger; return value is ignored
end;
$$;

do $$
begin
  if not exists (
    select 1
      from pg_trigger
     where tgname = 'syncpad_room_revisions_prune'
       and tgrelid = 'public.syncpad_room_revisions'::regclass
  ) then
    create trigger syncpad_room_revisions_prune
      after insert on public.syncpad_room_revisions
      for each row
      execute function public.prune_syncpad_room_revisions();
  end if;
end $$;

comment on table public.syncpad_room_revisions
  is 'Snapshots of syncpad_rooms.content for version history / restore. Pruned to the 50 most recent rows per room by the syncpad_room_revisions_prune trigger.';

-- ════════════════════════════════════════════════════════════════
-- OPTIONAL: Maintenance queries (run manually as needed)
-- ════════════════════════════════════════════════════════════════
--
-- -- 1) Count revisions per room, largest first
-- select room_id, count(*) as revision_count
-- from   public.syncpad_room_revisions
-- group by room_id
-- order by revision_count desc
-- limit 50;
--
-- -- 2) Total storage used by revision content, in bytes (approx)
-- select sum(octet_length(content)) as approx_bytes
-- from   public.syncpad_room_revisions;


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0005_device_limit.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Device Limit Migration ("burn after N devices join")
-- SAFE TO RERUN: all statements use CREATE IF NOT EXISTS,
-- CREATE OR REPLACE, and ALTER ... ADD COLUMN IF NOT EXISTS so
-- the script is fully idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER the
-- base 0001_base_schema.sql has been applied.
--
-- What this migration adds
-- ────────────────────────
--   A room-owner-configurable cap on how many distinct devices may ever
--   join a room before its content clears — a live-collaboration take on
--   burn-after-reading. The existing View-once feature already covers "the
--   first reader consumes it"; this generalizes that to "clears once N
--   different people have joined", which suits an actual multi-person
--   working session better than a single-reader model, while still
--   guaranteeing the room can't outlive its intended audience.
--
--   Deliberately NOT "expires when everyone disconnects" — that would
--   require server-side presence tracking (Supabase Presence is a Realtime-
--   only concept with no Postgres-visible state), which is a materially
--   bigger lift than a per-room settings field. Counting distinct joins is
--   reliable with the existing schema: it's decided once, synchronously, at
--   load time via a SECURITY DEFINER RPC — nothing has to observe an absence.
--
--   1. syncpad_rooms.device_limit — nullable int; null/0 means unlimited
--      (the existing default), matching how expires_at being null already
--      means "no expiry".
--
--   2. syncpad_room_seen_devices — one row per (room, device) that has ever
--      loaded the room, so re-joins by the same device never count twice.
--      RLS locked down like the other support tables (share links, room
--      codes) — only reachable through the RPC below.
--
--   3. record_room_device_view(room_id, device_id) — call once per room
--      load (after the creator/read-only exclusions the client already
--      applies for View-once, mirrored here). Idempotent per device;
--      returns whether this call was the one that hit the limit and
--      cleared the room, so the caller can still show the content it
--      already has in hand (same pattern as consumeViewOnce()).
-- ============================================================

alter table public.syncpad_rooms
  add column if not exists device_limit integer;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'syncpad_rooms_device_limit_check'
  ) then
    alter table public.syncpad_rooms
      add constraint syncpad_rooms_device_limit_check
      check (device_limit is null or (device_limit >= 1 and device_limit <= 50));
  end if;
end $$;

create table if not exists public.syncpad_room_seen_devices (
  room_id      text        not null references public.syncpad_rooms(room_id) on delete cascade,
  device_id    text        not null,
  first_seen_at timestamptz not null default now(),
  primary key (room_id, device_id)
);

alter table public.syncpad_room_seen_devices enable row level security;

drop policy if exists "anon no direct seen-device reads" on public.syncpad_room_seen_devices;
drop policy if exists "anon no direct seen-device writes" on public.syncpad_room_seen_devices;

create policy "anon no direct seen-device reads"
  on public.syncpad_room_seen_devices for select to anon using (false);
create policy "anon no direct seen-device writes"
  on public.syncpad_room_seen_devices for all to anon using (false) with check (false);

create or replace function public.record_room_device_view(p_room_id text, p_device_id text)
returns table(device_count int, device_limit int, expired boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit   int;
  v_count   int;
  v_expired boolean := false;
begin
  if p_room_id is null or btrim(p_room_id) = '' or p_device_id is null or btrim(p_device_id) = '' then
    return;
  end if;

  insert into public.syncpad_room_seen_devices(room_id, device_id)
  values (p_room_id, p_device_id)
  on conflict (room_id, device_id) do nothing;

  select r.device_limit into v_limit
    from public.syncpad_rooms r
   where r.room_id = p_room_id;

  select count(*) into v_count
    from public.syncpad_room_seen_devices sd
   where sd.room_id = p_room_id;

  if v_limit is not null and v_count >= v_limit then
    update public.syncpad_rooms
       set content = '',
           cleared_reason = 'device_limit',
           device_limit = null, -- one-shot: don't re-trigger once cleared
           -- Lets the client's isOwnWrite check (updated_by_device === my
           -- device id) recognize its own join as the trigger, the same
           -- signal it already uses to avoid wiping content it just earned
           -- the right to see — see app.js's _handleRoomStateTransition.
           updated_by_device = p_device_id
     where room_id = p_room_id
       and cleared_reason is distinct from 'device_limit';
    v_expired := true;
  end if;

  return query select v_count, v_limit, v_expired;
end;
$$;

grant execute on function public.record_room_device_view(text, text) to anon, authenticated;

comment on table public.syncpad_room_seen_devices
  is 'One row per distinct device that has ever loaded a room with device_limit set. Feeds record_room_device_view(), which clears the room once the count reaches the limit.';


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0006_admin_dashboard_improvements.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Admin Dashboard Improvements Migration
-- SAFE TO RERUN: all statements use CREATE IF NOT EXISTS,
-- ALTER … ADD COLUMN IF NOT EXISTS, CREATE OR REPLACE, and
-- DROP POLICY IF EXISTS / CREATE POLICY so the script is fully
-- idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER the
-- base 0001_base_schema.sql has been applied.
--
-- What this migration adds
-- ────────────────────────
--   1. syncpad_admin_audit_logs table
--      Persists a record of every action an admin takes so
--      there is a durable audit trail for compliance and
--      incident investigation.
--
--   2. Quarantine columns on syncpad_rooms
--      Lightweight first-class quarantine support:
--      quarantined_at, quarantined_by, quarantine_reason,
--      downloads_disabled.
--
--   3. Indexes on the new table and new columns.
--
--   4. RLS policies – admin-read-only on audit logs; admin-
--      only INSERT via a SECURITY DEFINER helper function.
--
--   5. log_admin_action() – SECURITY DEFINER RPC so the
--      frontend admin can write audit rows without a direct
--      INSERT policy that would expose the table to all
--      authenticated users.
--
--   6. admin_quarantine_room()   – RPC to quarantine a room.
--   7. admin_unquarantine_room() – RPC to lift a quarantine.
--
-- ⚠ FRONTEND-ONLY UNLESS YOU ALSO RUN 0008 ⚠
-- ─────────────────────────────────────────────────────────────
-- The quarantine feature added here is FRONTEND-ENFORCED on its own — a
-- determined user could bypass it by calling the Supabase REST API
-- directly with the anon key. Run 0008_quarantine_enforcement.sql too —
-- it adds a database trigger that rejects writes to a quarantined room
-- server-side, the same technique the room-lock feature already uses.
--
-- Similarly, downloads_disabled only blocks the frontend from
-- generating signed-URL requests.  The Storage bucket itself
-- still allows any anon user with a known object path to
-- request a signed URL unless a Storage policy is added to
-- deny requests for files whose room is quarantined.
-- ============================================================


-- ════════════════════════════════════════════════════════════════
-- SECTION 1 – syncpad_admin_audit_logs
-- ════════════════════════════════════════════════════════════════
-- Every admin action (clear, delete, quarantine, review report,
-- etc.) should call log_admin_action() (defined in Section 4)
-- immediately after the action succeeds or fails.  The row is
-- immutable once written — no UPDATE or DELETE is ever issued
-- against this table except by a superuser performing emergency
-- corrections.

create table if not exists public.syncpad_admin_audit_logs (
  -- Surrogate primary key – universally unique, client-free.
  id               uuid        primary key default gen_random_uuid(),

  -- The email address of the authenticated admin who performed
  -- the action.  Stored as plain text (not a FK to auth.users)
  -- so the record survives even if the admin account is later
  -- removed.  Populated by log_admin_action() from
  -- auth.email() at call time.
  admin_email      text,

  -- Machine-readable action identifier.
  -- Suggested values (extend as needed):
  --   'clear_room'         – admin cleared a room's content
  --   'delete_room'        – admin permanently deleted a room
  --   'quarantine_room'    – admin quarantined a room
  --   'unquarantine_room'  – admin lifted quarantine on a room
  --   'delete_file'        – admin deleted a file attachment
  --   'review_report'      – admin changed a report's status
  --   'dismiss_report'     – admin dismissed a report
  --   'lock_room'          – admin set editing_locked = true
  --   'unlock_room'        – admin set editing_locked = false
  --   'disable_downloads'  – admin set downloads_disabled = true
  --   'enable_downloads'   – admin set downloads_disabled = false
  --   'run_cleanup'        – admin triggered expired-room cleanup
  action_type      text        not null,

  -- Optional FK to the affected room.  SET NULL on room deletion
  -- so the audit record survives even after the room is gone.
  target_room_id   text        references public.syncpad_rooms(room_id) on delete set null,

  -- Optional identifiers for affected file or report rows.
  -- Stored as plain uuid rather than FK so the log row survives
  -- after the target row is deleted.
  target_file_id   uuid,
  target_report_id uuid,

  -- 'success' | 'failure'
  -- Use 'failure' + error_msg when catching exceptions in the
  -- calling PL/pgSQL or the frontend.
  result           text        not null default 'success',
  error_msg        text,

  -- Free-form JSON for any extra context (IP address captured
  -- by the Edge Function, before/after values, etc.).
  -- Keep PII out of here – store only operationally relevant
  -- data.
  metadata         jsonb,

  created_at       timestamptz not null default now()
);

comment on table public.syncpad_admin_audit_logs
  is 'Immutable audit trail of every action performed by a SyncPad admin. Written via log_admin_action(); never updated or deleted by the app.';

comment on column public.syncpad_admin_audit_logs.action_type
  is 'Machine-readable action type. Suggested values: clear_room, delete_room, quarantine_room, unquarantine_room, delete_file, review_report, dismiss_report, lock_room, unlock_room, disable_downloads, enable_downloads, run_cleanup.';

comment on column public.syncpad_admin_audit_logs.result
  is 'Outcome of the action: ''success'' (default) or ''failure''. On failure, populate error_msg.';

comment on column public.syncpad_admin_audit_logs.metadata
  is 'Optional free-form JSONB for extra context (e.g. before/after values). Keep PII out.';


-- ════════════════════════════════════════════════════════════════
-- SECTION 2 – Quarantine columns on syncpad_rooms
-- ════════════════════════════════════════════════════════════════
-- These columns are all nullable / defaulting to false so that
-- existing rows are unaffected by the migration.
--
-- Usage in frontend (src/app.js or src/ui.js):
--   if (room.quarantined_at) {
--     // Show "This room has been quarantined" blocking screen.
--     // Do not render the editor or file list.
--   }
--   if (room.downloads_disabled) {
--     // Hide / disable all "Download" buttons in the files panel.
--   }
--
-- See the FRONTEND-ONLY SECURITY WARNING in the file header for
-- the limitations of this approach and how to harden it with RLS.

-- Timestamp when the room was quarantined.
-- NULL means the room is NOT quarantined.
-- Non-null means it IS quarantined — check this column first.
alter table public.syncpad_rooms
  add column if not exists quarantined_at timestamptz;

-- The admin email (or device id / system identifier) that
-- triggered the quarantine, for audit cross-reference.
alter table public.syncpad_rooms
  add column if not exists quarantined_by text;

-- Free-text reason recorded at quarantine time for display in
-- the admin dashboard and optionally to the end user.
alter table public.syncpad_rooms
  add column if not exists quarantine_reason text;

-- When true the frontend should suppress all signed-URL
-- generation and file download links for this room.
-- Note: this does NOT prevent direct Storage API calls.
-- Pair with a Storage policy if server-side enforcement is
-- needed (see FRONTEND-ONLY SECURITY WARNING).
alter table public.syncpad_rooms
  add column if not exists downloads_disabled boolean not null default false;

comment on column public.syncpad_rooms.quarantined_at
  is 'Non-null when the room is quarantined. The frontend checks this column and shows a blocked-room screen. See admin-dashboard-improvements.sql for server-side enforcement notes.';

comment on column public.syncpad_rooms.quarantined_by
  is 'Email or identifier of the admin who quarantined the room. Populated by admin_quarantine_room().';

comment on column public.syncpad_rooms.quarantine_reason
  is 'Human-readable reason for the quarantine, shown in the admin dashboard.';

comment on column public.syncpad_rooms.downloads_disabled
  is 'When true, the frontend suppresses file download links for this room. Server-side enforcement requires an additional Storage policy (see migration header).';


-- ════════════════════════════════════════════════════════════════
-- SECTION 3 – Indexes
-- ════════════════════════════════════════════════════════════════

-- Audit logs: time-range scans are the most common admin query
-- ("show me all actions in the last 24 hours").
create index if not exists idx_audit_logs_created_at
  on public.syncpad_admin_audit_logs(created_at desc);

-- Audit logs: filter by admin who performed the action.
create index if not exists idx_audit_logs_admin_email
  on public.syncpad_admin_audit_logs(admin_email);

-- Audit logs: look up all actions that touched a specific room.
create index if not exists idx_audit_logs_target_room_id
  on public.syncpad_admin_audit_logs(target_room_id)
  where target_room_id is not null;

-- Audit logs: look up all actions of a specific type
-- (e.g. "show all quarantine events").
create index if not exists idx_audit_logs_action_type
  on public.syncpad_admin_audit_logs(action_type);

-- Rooms: fast lookup of quarantined rooms (a common admin dashboard
-- view).  The partial index only covers rows where the column is
-- non-null, keeping it small.
create index if not exists idx_syncpad_rooms_quarantined_at
  on public.syncpad_rooms(quarantined_at)
  where quarantined_at is not null;

-- Rooms: fast lookup of rooms with downloads disabled.
create index if not exists idx_syncpad_rooms_downloads_disabled
  on public.syncpad_rooms(downloads_disabled)
  where downloads_disabled = true;


-- ════════════════════════════════════════════════════════════════
-- SECTION 4 – RLS policies for syncpad_admin_audit_logs
-- ════════════════════════════════════════════════════════════════
-- Design decisions:
--
--   • Anon users: NO access at all.  The table must never be
--     readable or writable by unauthenticated requests.
--
--   • Authenticated non-admin users: read the policies below.
--     The baseline policies in 0001_base_schema.sql do NOT grant
--     baseline access to this table, so the default deny applies
--     to non-admin authenticated users.
--
--   • Authenticated admin users: SELECT only via RLS.
--     INSERT is handled exclusively through log_admin_action()
--     (a SECURITY DEFINER function defined in this section), so
--     there is no direct INSERT policy exposed to the role.
--     This prevents an admin from crafting arbitrary log rows
--     that contradict the server-recorded truth.
--
--   • UPDATE / DELETE: no policy is created, so both are denied
--     to all roles by default.  Audit rows are immutable.

alter table public.syncpad_admin_audit_logs enable row level security;

-- Anon: explicit deny for every operation (belt-and-suspenders;
-- default deny already applies but we make the intent clear).
drop policy if exists "anon no audit log reads"  on public.syncpad_admin_audit_logs;
drop policy if exists "anon no audit log writes" on public.syncpad_admin_audit_logs;
create policy "anon no audit log reads"
  on public.syncpad_admin_audit_logs for select to anon
  using (false);
create policy "anon no audit log writes"
  on public.syncpad_admin_audit_logs for all to anon
  using (false) with check (false);

-- Admin: SELECT only.  INSERT goes through log_admin_action().
drop policy if exists "admin read audit logs" on public.syncpad_admin_audit_logs;
create policy "admin read audit logs"
  on public.syncpad_admin_audit_logs for select to authenticated
  using (public.is_syncpad_admin());

-- No INSERT policy is created for the authenticated role here.
-- All inserts must go through log_admin_action() below, which
-- runs as SECURITY DEFINER and bypasses RLS for the insert.


-- ── log_admin_action() ────────────────────────────────────────
-- SECURITY DEFINER: runs as the function owner (postgres), not
-- as the calling role, so it can INSERT into the audit log
-- regardless of RLS.  The caller's identity is verified by
-- is_syncpad_admin() before the insert proceeds.
--
-- Parameters
--   p_action_type      – required; see action_type comment above
--   p_target_room_id   – optional room that was acted on
--   p_target_file_id   – optional file that was acted on
--   p_target_report_id – optional report that was acted on
--   p_result           – 'success' (default) or 'failure'
--   p_error_msg        – error detail when p_result = 'failure'
--   p_metadata         – any extra JSONB context
--
-- Returns the uuid of the newly created audit log row.
--
-- Frontend usage (src/admin.js):
--   const { data } = await supabase.rpc('log_admin_action', {
--     p_action_type:    'delete_room',
--     p_target_room_id: roomId,
--     p_result:         'success',
--   });

create or replace function public.log_admin_action(
  p_action_type      text,
  p_target_room_id   text    default null,
  p_target_file_id   uuid    default null,
  p_target_report_id uuid    default null,
  p_result           text    default 'success',
  p_error_msg        text    default null,
  p_metadata         jsonb   default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id         uuid;
  v_admin_email text;
begin
  -- Gate: only admins may write audit logs.
  if not public.is_syncpad_admin() then
    raise exception 'log_admin_action: caller is not a SyncPad admin';
  end if;

  -- Capture the calling admin's email from the JWT claim.
  -- auth.email() is available in SECURITY DEFINER context.
  v_admin_email := auth.email();

  insert into public.syncpad_admin_audit_logs (
    admin_email,
    action_type,
    target_room_id,
    target_file_id,
    target_report_id,
    result,
    error_msg,
    metadata
  ) values (
    v_admin_email,
    p_action_type,
    p_target_room_id,
    p_target_file_id,
    p_target_report_id,
    coalesce(p_result, 'success'),
    p_error_msg,
    p_metadata
  )
  returning id into v_id;

  return v_id;
end;
$$;

comment on function public.log_admin_action(text, text, uuid, uuid, text, text, jsonb)
  is 'SECURITY DEFINER: verifies the caller is a SyncPad admin then inserts an immutable audit-log row. All admin actions should call this immediately after they complete.';

-- Grant EXECUTE to authenticated so admin users can call it via RPC.
-- Anon access is intentionally withheld.
grant execute on function public.log_admin_action(text, text, uuid, uuid, text, text, jsonb)
  to authenticated;

revoke execute on function public.log_admin_action(text, text, uuid, uuid, text, text, jsonb)
  from anon;


-- ════════════════════════════════════════════════════════════════
-- SECTION 5 – admin_quarantine_room()
-- ════════════════════════════════════════════════════════════════
-- Sets quarantined_at, quarantined_by, and quarantine_reason on
-- the target room, then writes an audit log row.
--
-- Parameters
--   p_room_id      – room_id of the room to quarantine (required)
--   p_reason       – human-readable reason (required)
--   p_quarantined_by – admin email or identifier (required)
--
-- Raises an exception if:
--   • the caller is not an admin
--   • p_room_id does not match any existing room
--
-- Returns void.  The frontend should check for a Postgres
-- exception and display an error toast if one is raised.
--
-- Frontend usage (src/admin.js):
--   await supabase.rpc('admin_quarantine_room', {
--     p_room_id:        roomId,
--     p_reason:         'Spam / harmful content',
--     p_quarantined_by: currentAdminEmail,
--   });

create or replace function public.admin_quarantine_room(
  p_room_id        text,
  p_reason         text,
  p_quarantined_by text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows_affected integer;
begin
  -- ── Auth check ───────────────────────────────────────────────
  if not public.is_syncpad_admin() then
    raise exception 'admin_quarantine_room: caller is not a SyncPad admin';
  end if;

  -- ── Validate inputs ──────────────────────────────────────────
  if p_room_id is null or btrim(p_room_id) = '' then
    raise exception 'admin_quarantine_room: p_room_id must not be null or empty';
  end if;

  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'admin_quarantine_room: p_reason must not be null or empty';
  end if;

  if p_quarantined_by is null or btrim(p_quarantined_by) = '' then
    raise exception 'admin_quarantine_room: p_quarantined_by must not be null or empty';
  end if;

  -- ── Apply quarantine ─────────────────────────────────────────
  update public.syncpad_rooms
     set quarantined_at     = now(),
         quarantined_by     = p_quarantined_by,
         quarantine_reason  = p_reason,
         -- Automatically disable downloads when quarantined.
         -- The admin can re-enable them independently via a
         -- separate update if the room is later reviewed.
         downloads_disabled = true
   where room_id = p_room_id;

  get diagnostics v_rows_affected = row_count;

  if v_rows_affected = 0 then
    raise exception 'admin_quarantine_room: room % not found', p_room_id;
  end if;

  -- ── Write audit log ──────────────────────────────────────────
  -- Fires synchronously so the log row and the quarantine update
  -- are in the same transaction.  If this call raises, the whole
  -- transaction is rolled back, which is the correct behaviour.
  perform public.log_admin_action(
    p_action_type    => 'quarantine_room',
    p_target_room_id => p_room_id,
    p_result         => 'success',
    p_metadata       => jsonb_build_object(
                          'reason',         p_reason,
                          'quarantined_by', p_quarantined_by
                        )
  );
end;
$$;

comment on function public.admin_quarantine_room(text, text, text)
  is 'SECURITY DEFINER: quarantines a room by setting quarantined_at and related columns, then writes an audit log row. Raises an exception for non-admin callers or missing rooms.';

grant execute on function public.admin_quarantine_room(text, text, text)
  to authenticated;

revoke execute on function public.admin_quarantine_room(text, text, text)
  from anon;


-- ════════════════════════════════════════════════════════════════
-- SECTION 6 – admin_unquarantine_room()
-- ════════════════════════════════════════════════════════════════
-- Clears all quarantine columns on the target room and writes an
-- audit log row.  Downloads are re-enabled automatically.
--
-- Parameters
--   p_room_id – room_id of the room to unquarantine (required)
--
-- Raises an exception if:
--   • the caller is not an admin
--   • p_room_id does not match any existing room
--
-- Returns void.
--
-- Frontend usage (src/admin.js):
--   await supabase.rpc('admin_unquarantine_room', {
--     p_room_id: roomId,
--   });

create or replace function public.admin_unquarantine_room(
  p_room_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows_affected integer;
begin
  -- ── Auth check ───────────────────────────────────────────────
  if not public.is_syncpad_admin() then
    raise exception 'admin_unquarantine_room: caller is not a SyncPad admin';
  end if;

  -- ── Validate input ───────────────────────────────────────────
  if p_room_id is null or btrim(p_room_id) = '' then
    raise exception 'admin_unquarantine_room: p_room_id must not be null or empty';
  end if;

  -- ── Clear quarantine ─────────────────────────────────────────
  update public.syncpad_rooms
     set quarantined_at     = null,
         quarantined_by     = null,
         quarantine_reason  = null,
         downloads_disabled = false
   where room_id = p_room_id;

  get diagnostics v_rows_affected = row_count;

  if v_rows_affected = 0 then
    raise exception 'admin_unquarantine_room: room % not found', p_room_id;
  end if;

  -- ── Write audit log ──────────────────────────────────────────
  perform public.log_admin_action(
    p_action_type    => 'unquarantine_room',
    p_target_room_id => p_room_id,
    p_result         => 'success'
  );
end;
$$;

comment on function public.admin_unquarantine_room(text)
  is 'SECURITY DEFINER: lifts quarantine on a room by clearing quarantined_at and related columns, re-enables downloads, then writes an audit log row. Raises an exception for non-admin callers or missing rooms.';

grant execute on function public.admin_unquarantine_room(text)
  to authenticated;

revoke execute on function public.admin_unquarantine_room(text)
  from anon;


-- ════════════════════════════════════════════════════════════════
-- SECTION 7 – Frontend integration notes (non-executable)
-- ════════════════════════════════════════════════════════════════
--
-- 1. CHECKING QUARANTINE IN THE APP
--    After loading a room row, check:
--
--      if (room.quarantined_at) {
--        UI.showQuarantinedScreen(room.quarantine_reason);
--        return;   // do not proceed to render the editor
--      }
--
--    The quarantine check should happen before any decryption
--    attempt, passcode prompt, or editor initialisation.
--
-- 2. CHECKING DOWNLOADS_DISABLED
--    Before calling src/files.js to generate a signed URL:
--
--      if (room.downloads_disabled) {
--        // Hide "Download" buttons; do not call getSignedUrl().
--      }
--
-- 3. CALLING THE QUARANTINE RPCs FROM src/admin.js
--
--      // Quarantine
--      const { error } = await supabase.rpc('admin_quarantine_room', {
--        p_room_id:        roomId,
--        p_reason:         reason,
--        p_quarantined_by: adminEmail,
--      });
--
--      // Unquarantine
--      const { error } = await supabase.rpc('admin_unquarantine_room', {
--        p_room_id: roomId,
--      });
--
-- 4. LOGGING CUSTOM ADMIN ACTIONS
--    For actions not handled by the quarantine RPCs (e.g.
--    clearing a room, reviewing a report), call:
--
--      await supabase.rpc('log_admin_action', {
--        p_action_type:    'clear_room',     // or 'review_report', etc.
--        p_target_room_id: roomId,
--        p_result:         'success',
--        p_metadata:       { cleared_reason: 'manual' },
--      });
--
-- 5. SERVER-SIDE QUARANTINE ENFORCEMENT
--    Run 0008_quarantine_enforcement.sql — a BEFORE UPDATE trigger on
--    syncpad_rooms (same technique as this migration's own room-lock
--    trigger) that rejects writes to a quarantined room regardless of
--    which policy or code path let the request through. See the
--    FRONTEND-ONLY WARNING at the top of this file for why that matters.
--
-- ════════════════════════════════════════════════════════════════
-- END OF MIGRATION
-- ════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════
-- SOURCE: supabase/migrations/0008_quarantine_enforcement.sql
-- ════════════════════════════════════════════════════════════════

-- ============================================================
-- SyncPad – Quarantine Enforcement Migration
-- SAFE TO RERUN: CREATE OR REPLACE / DROP+CREATE TRIGGER guarded by
-- existence checks, fully idempotent.
--
-- Run this in your Supabase project → SQL Editor AFTER
-- 0006_admin_dashboard_improvements.sql (adds quarantined_at) has been
-- applied. Does NOT require 0007_room_edit_tokens.sql.
--
-- What this migration adds
-- ────────────────────────
-- 0006's own header ships an explicit "FRONTEND-ONLY" warning: quarantine
-- had nothing server-side checking it, so a determined user could bypass
-- it by calling the API directly with the anon key.
--
-- This closes that gap with a BEFORE UPDATE trigger — the same technique
-- 0001's enforce_syncpad_rooms_lock() already uses for the room-lock
-- feature — rather than routing writes through a choke-point RPC. A
-- trigger fires on every UPDATE to syncpad_rooms regardless of which
-- policy or code path permitted it, so it stays correct no matter how
-- room writes are gated at the RLS layer (this migration was originally
-- written against rpc_update_room() from 0007_room_edit_tokens.sql; see
-- 0009_revert_edit_token_write_gating.sql for why that RPC is no longer
-- the client's write path — the trigger approach here doesn't have that
-- dependency at all).
--
-- A signed-in admin (is_syncpad_admin()) still bypasses this, same as the
-- room-lock trigger — quarantine and lock are both meant to stop everyone
-- EXCEPT the admin who set them. The backend cleanup job is exempt too,
-- for the same reason the lock trigger exempts it: an expired room should
-- still be sweepable even if it's also quarantined.
-- ============================================================

create or replace function public.enforce_syncpad_rooms_quarantine()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if OLD.quarantined_at is not null
     and coalesce(NEW.updated_by_device, '') <> 'backend-cleanup'
     and not public.is_syncpad_admin()
  then
    raise exception 'This room has been quarantined and cannot be edited.' using errcode = '42501';
  end if;
  return NEW;
end;
$$;

drop trigger if exists syncpad_rooms_enforce_quarantine on public.syncpad_rooms;

create trigger syncpad_rooms_enforce_quarantine
  before update on public.syncpad_rooms
  for each row
  execute function public.enforce_syncpad_rooms_quarantine();
